pub type Character = [[bool; 8]; 16];

// TODO: this is one way to get a simple font in your program.
//       finish this if you want to use it properly. Also add
//       functions to screen.rs to draw a `Character`
pub const ZERO: Character = [
    [false, true, true, true, true, true, true, false],
    [true, true, true, true, true, true, true, true],
    [true, true, true, false, false, true, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, true, false, false, true, true, true],
    [true, true, true, true, true, true, true, true],
    [false, true, true, true, true, true, true, false],
];

pub const ONE: Character = [
    [false, false, false, true, true, false, false, false],
    [false, false, true, true, true, false, false, false],
    [false, true, true, true, true, false, false, false],
    [true, true, false, true, true, false, false, false],
    [false, false, false, true, true, false, false, false],
    [false, false, false, true, true, false, false, false],
    [false, false, false, true, true, false, false, false],
    [false, false, false, true, true, false, false, false],
    [false, false, false, true, true, false, false, false],
    [false, false, false, true, true, false, false, false],
    [false, false, false, true, true, false, false, false],
    [false, false, false, true, true, false, false, false],
    [false, false, false, true, true, false, false, false],
    [true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true], 
    [false, false, false, false, false, false, false, false],
];

pub const TWO: Character = [
    [false, true, true, true, true, true, true, false],
    [true, true, true, true, true, true, true, true],
    [true, true, false, false, false, false, true, true],
    [false, false, false, false, false, false, true, true],
    [false, false, false, false, false, true, true, false],
    [false, false, false, false, true, true, false, false],
    [false, false, false, true, true, false, false, false],
    [false, false, true, true, false, false, false, false],
    [false, true, true, false, false, false, false, false],
    [true, true, false, false, false, false, false, false],
    [true, true, false, false, false, false, false, false],
    [true, true, false, false, false, false, false, false],
    [true, true, false, false, false, false, false, false],
    [true, true, true, true, true, true, true, true],
    [true, true,true ,true ,true ,true ,true ,true ],
    [false ,false ,false ,false ,false ,false ,false ,false ],
];

pub const THREE: Character = [
    [false, true, true, true, true, true, true, false],
    [true, true, true, true, true, true, true, true],
    [true, true, false, false, false, false, true, true],
    [false, false, false, false, false, false, true, true],
    [false, false, false, false, false, true, true, false],
    [false, false, false, false, true, true, false, false],
    [false, false, false, true, true, false, false, false],
    [false, false, true, true, true, true, true, false],
    [false, false, false, false, false, false, true, false],
    [false, false, false, false, false, false, true, true],
    [false ,false ,false ,false ,false ,false ,true ,true ],
    [true ,true ,false ,false ,false ,false ,true ,true ],
    [true ,true ,false ,false ,false ,false ,true ,true ],
    [true ,true ,true ,true ,true ,true ,true ,true ],
    [true ,true ,true ,true ,true ,true ,true ,true ],
    [false ,false ,false ,false ,false ,false ,false ,false ],
];

pub const FOUR: Character = [
    [false ,false ,false ,false ,true ,true ,false ,false ],
    [false ,false ,false ,true ,true ,true ,false ,false ],
    [false ,false ,true ,true ,true ,true ,false ,false ],
    [false ,true ,true ,false ,true ,true ,false ,false ],
    [true ,true ,false ,false ,true ,true ,false ,false ],
    [true ,true ,false ,false ,true ,true ,false ,false ],
    [true ,true ,false ,false ,true ,true ,false ,false ],
    [true ,true ,true ,true ,true ,true ,true ,true ],
    [true ,true ,true ,true ,true ,true ,true ,true ],
    [false ,false ,false ,false ,true ,true ,false ,false ],
    [false ,false ,false ,false ,true ,true ,false ,false ],
    [false ,false ,false ,false ,true ,true ,false ,false ],
    [false ,false ,false ,false ,true ,true, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
];

pub const FIVE: Character = [
    [true ,true ,true ,true ,true ,true ,true ,true ],
    [true ,true ,true ,true ,true ,true ,true ,true ],
    [true ,true ,false ,false ,false ,false ,false ,false ],
    [true ,true ,false ,false ,false ,false ,false ,false ],
    [true ,true ,true ,true ,true ,true ,true ,false ],
    [true ,true ,true ,true ,true ,true ,true ,true ],
    [false ,false ,false ,false ,false ,false ,true ,true ],
    [false ,false ,false ,false ,false ,false ,true ,true ],
    [false ,false ,false ,false ,false ,false ,true ,true ],
    [false ,false ,false ,false ,false, false, true, true],
    [false, false, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true],
    [false, false, false, false, false, false, false, false],
];

pub const SIX: Character = [
    [false, true, true, true, true, true, true, false],
    [true, true, true, true, true, true, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, false, false],
    [true, true, true, true, true, true, true, false],
    [true, true, true, true, true, true, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true ,true ,false ,false ,false ,false ,true ,true ],
    [true ,true ,false ,false ,false ,false ,true ,true ],
    [true ,true ,false ,false ,false ,false ,true ,true ],
    [true ,true ,false ,false ,false ,false ,true ,true ],
    [true ,true ,true ,true ,true ,true ,true ,true ],
    [true ,true ,true ,true ,true ,true ,true ,false ],
    [false ,false ,false ,false ,false ,false ,false ,false ],
];

pub const SEVEN: Character = [
    [true ,true ,true ,true ,true ,true ,true ,true ],
    [true ,true ,true ,true ,true ,true ,true ,true ],
    [false ,false ,false ,false ,false ,false ,true ,true ],
    [false ,false ,false ,false ,false ,true ,true ,false ],
    [false ,false ,false ,false ,true ,true ,false ,false ],
    [false ,false ,false ,true ,true ,false ,false ,false ],
    [false ,false ,true ,true ,false ,false ,false ,false ],
    [false ,true ,true ,false ,false ,false ,false ,false ],
    [true ,true ,false ,false ,false ,false ,false ,false ],
    [true ,true ,false ,false ,false ,false, false, false],
    [true, true, false, false, false, false, false, false],
    [true, true, false, false, false, false, false, false],
    [true, true, false, false, false, false, false, false],
    [true, true, false, false, false, false, false, false],
    [true, true, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
];  

pub const EIGHT: Character = [
    [false ,true ,true ,true ,true ,true ,true ,false ],
    [true ,true ,true ,true ,true ,true ,true ,true ],
    [true ,true ,false ,false ,false ,false ,true ,true ],
    [true ,true ,false ,false ,false ,false ,true ,true ],
    [true ,true ,false ,false ,false ,false ,true ,true ],
    [true ,true ,false ,false ,false ,false ,true ,true ],
    [true ,true ,true ,true ,true ,true ,true ,true ],
    [true ,true ,true ,true ,true ,true ,true ,true ],
    [true ,true ,false ,false ,false ,false ,true ,true ],
    [true ,true ,false ,false ,false ,false ,true ,true ],
    [true ,true ,false ,false ,false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, false],
    [false, false, false, false, false, false, false, false],
];  

pub const NINE: Character = [
    [false ,true ,true ,true ,true ,true ,true ,false ],
    [true ,true ,true ,true ,true ,true ,true ,true ],
    [true ,true ,false ,false ,false ,false ,true ,true ],
    [true ,true ,false ,false ,false ,false ,true ,true ],
    [true ,true ,false ,false ,false ,false ,true ,true ],
    [true ,true ,false ,false ,false ,false ,true ,true ],
    [true ,true ,true ,true ,true ,true ,true ,true ],
    [false ,false ,false ,false ,false ,false ,true ,true ],
    [false ,false ,false ,false ,false ,false ,true ,true ],
    [false ,false ,false ,false, false, false, true, true],
    [false, false, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, false],
    [false, false, false, false, false, false, false, false],
];      

pub const NUMBERS: [Character; 10] = [
    ZERO,
    ONE,
    TWO,
    THREE,
    FOUR,
    FIVE,
    SIX,
    SEVEN,
    EIGHT,
    NINE,
];
